language: go
sudo: false
go:
  - 1.12.x

# env:
#   - GO111MODULE=on

os:
  - linux
  - osx

before_install:
  - go get -v ./cmd/...

script:
    # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  # run tests on a standard platform
  - go test -v ./...

  # run tests with the race detector as well
  - go test -race -v ./...