language: go
sudo: false
go:
  - 1.12.x

# env:
#   - GO111MODULE=on

os:
  - linux
  - osx

script:

  # run tests on a standard platform
  - go test -v ./...

  # run tests with the race detector as well
  - go test -race -v ./...